# Generated by Django 4.2 on 2024-04-28 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_friend_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['timestamp', 'name']},
        ),
    ]
