# Generated by Django 4.2 on 2024-04-29 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_conversation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-timestamp', 'name']},
        ),
    ]
