# Generated by Django 4.2 on 2024-04-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_conversation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['timestamp', 'name']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='aes_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_content',
            field=models.BinaryField(default=b''),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
