# Generated by Django 4.2 on 2024-04-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='encrypted_content',
            field=models.CharField(max_length=200),
        ),
    ]
